import type { User, Course, Certificate, Plan, AdminStats } from "./types"

export const mockUser: User = {
  id: "1",
  name: "Juan Pérez",
  email: "juan@example.com",
  avatar: "/diverse-user-avatars.png",
  role: "student",
  enrolledCourses: ["1", "2", "3"],
  completedCourses: ["1"],
  certificates: ["cert-1"],
  progress: {
    "1": 100,
    "2": 45,
    "3": 20,
  },
}

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "HTML & CSS Fundamentals",
    description: "Aprende los fundamentos de HTML y CSS desde cero. Crea sitios web modernos y responsivos.",
    category: "Web Development",
    level: "beginner",
    duration: "8 horas",
    lessons: 24,
    students: 15420,
    rating: 4.8,
    thumbnail: "/html-css-course.png",
    instructor: "María García",
    price: 0,
    isFree: true,
    tags: ["HTML", "CSS", "Web Design"],
  },
  {
    id: "2",
    title: "JavaScript Moderno",
    description: "Domina JavaScript ES6+ y aprende a crear aplicaciones web interactivas y dinámicas.",
    category: "Programming",
    level: "intermediate",
    duration: "12 horas",
    lessons: 36,
    students: 12350,
    rating: 4.9,
    thumbnail: "/javascript-programming.png",
    instructor: "Carlos Rodríguez",
    price: 49.99,
    isFree: false,
    tags: ["JavaScript", "ES6", "Programming"],
  },
  {
    id: "3",
    title: "React desde Cero",
    description: "Construye aplicaciones web modernas con React. Aprende hooks, context y mejores prácticas.",
    category: "Frontend",
    level: "intermediate",
    duration: "15 horas",
    lessons: 42,
    students: 9870,
    rating: 4.7,
    thumbnail: "/react-frontend.jpg",
    instructor: "Ana Martínez",
    price: 69.99,
    isFree: false,
    tags: ["React", "Frontend", "JavaScript"],
  },
  {
    id: "4",
    title: "Python para Principiantes",
    description: "Inicia tu viaje en programación con Python. Aprende sintaxis, estructuras de datos y más.",
    category: "Programming",
    level: "beginner",
    duration: "10 horas",
    lessons: 30,
    students: 18500,
    rating: 4.6,
    thumbnail: "/python-programming-concept.png",
    instructor: "Luis Fernández",
    price: 0,
    isFree: true,
    tags: ["Python", "Programming", "Beginner"],
  },
  {
    id: "5",
    title: "Node.js y Express",
    description: "Crea APIs RESTful y aplicaciones backend escalables con Node.js y Express.",
    category: "Backend",
    level: "advanced",
    duration: "14 horas",
    lessons: 38,
    students: 7650,
    rating: 4.8,
    thumbnail: "/nodejs-backend.png",
    instructor: "Pedro Sánchez",
    price: 79.99,
    isFree: false,
    tags: ["Node.js", "Express", "Backend"],
  },
  {
    id: "6",
    title: "SQL y Bases de Datos",
    description: "Domina SQL y aprende a diseñar, consultar y optimizar bases de datos relacionales.",
    category: "Database",
    level: "intermediate",
    duration: "11 horas",
    lessons: 32,
    students: 11200,
    rating: 4.7,
    thumbnail: "/sql-database.png",
    instructor: "Laura Torres",
    price: 54.99,
    isFree: false,
    tags: ["SQL", "Database", "Backend"],
  },
]

export const mockCertificates: Certificate[] = [
  {
    id: "cert-1",
    userId: "1",
    courseId: "1",
    courseName: "HTML & CSS Fundamentals",
    completedDate: "2024-01-15",
    certificateUrl: "#",
  },
]

export const mockPlans: Plan[] = [
  {
    id: "free",
    name: "Gratis",
    price: 0,
    period: "monthly",
    features: ["Acceso a cursos gratuitos", "Certificados básicos", "Comunidad de estudiantes", "Soporte por email"],
  },
  {
    id: "pro",
    name: "Pro",
    price: 29.99,
    period: "monthly",
    popular: true,
    features: [
      "Acceso a todos los cursos",
      "Certificados profesionales",
      "Proyectos prácticos",
      "Soporte prioritario",
      "Descarga de recursos",
      "Sin anuncios",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 99.99,
    period: "monthly",
    features: [
      "Todo lo de Pro",
      "Cursos personalizados",
      "Mentoría 1-a-1",
      "Certificaciones avanzadas",
      "API de integración",
      "Dashboard de equipo",
    ],
  },
]

export const mockAdminStats: AdminStats = {
  totalUsers: 45230,
  totalCourses: 156,
  totalRevenue: 892450,
  activeStudents: 12340,
}
